FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
  python3 python3-pip make g++ \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci

COPY . .
CMD ["npm", "run", "dev"]


