FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm config set registry https://registry.npmjs.org/ \
 && npm config delete proxy || true \
 && npm config delete https-proxy || true \
 && npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]